# Device-only stock-QKV differential for the fused emitted ALBERT attention3 region.
$root=[IO.Path]::Combine($Activity.FilesDir.AbsolutePath,'kokoro-fl');$dir=[IO.Path]::Combine($root,'albert-attention3-emitted');$receipt=[IO.Path]::Combine($dir,'receipt.txt')
$lines=[Collections.Generic.List[string]]::new();$lines.Add('Job=kokoro-albert-attention3-emitted');$save={[IO.File]::WriteAllLines($receipt,$lines)};$hash={param([byte[]]$Bytes)[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($Bytes))}
$M=[Runtime.InteropServices.Marshal];$native=[IntPtr]::Zero;$opened=$false;$passed=$false;$pins=[Collections.Generic.List[object]]::new();$allocations=[Collections.Generic.List[object]]::new()
try{
    $modulePath=[IO.Path]::Combine($root,'Native.Binding.psm1');if((& $hash ([IO.File]::ReadAllBytes($modulePath))) -ne '7A42BF2FE487C303116E315CA594736B2D3FDA24FE2741618736427AB062E89F'){throw 'Delegate factory pin mismatch'}
    $tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($modulePath,[ref]$tokens,[ref]$errors);if($errors.Count){throw 'Delegate factory parse failed'};$abi=$ast.GetScriptBlock().InvokeReturnAsIs()
    $so=[IO.Path]::Combine($root,'qnn','libkokoro_albert_attention3_skel.so');if((& $hash ([IO.File]::ReadAllBytes($so))) -ne '36E9FF41F6F622B27B8725DDB7E1ADA687C6D315F7C8034606BC38DF3904CF9F'){throw 'Emitted library pin mismatch'}
    $manifestBytes=[IO.File]::ReadAllBytes([IO.Path]::Combine($dir,'fixture.json'));if((& $hash $manifestBytes) -ne '08E767B7482C755CA70C59F53A9F69040DFE626AE290206FE3C4566978DEA76E'){throw 'Fixture manifest pin mismatch'}
    $document=[Text.Json.JsonDocument]::Parse([Text.Encoding]::UTF8.GetString($manifestBytes));$fixture=$document.RootElement;if($fixture.GetProperty('Role').GetString() -ne 'stock_albert_attention3_differential_fixture' -or $fixture.GetProperty('Tokens').GetInt32() -ne 3 -or $fixture.GetProperty('Heads').GetInt32() -ne 12 -or $fixture.GetProperty('HeadWidth').GetInt32() -ne 64){throw 'Fixture contract differs'}
    $load={param([string]$Property)$record=$fixture.GetProperty($Property);$bytes=[IO.File]::ReadAllBytes([IO.Path]::Combine($dir,$record.GetProperty('Name').GetString()));if($bytes.Length-ne$record.GetProperty('Bytes').GetInt32()-or(& $hash $bytes)-ne$record.GetProperty('SHA256').GetString()){throw 'Fixture payload integrity differs'};$bytes}
    [byte[]]$inputBytes=& $load 'Input';[byte[]]$expectedBytes=& $load 'Expected';[byte[]]$output=[byte[]]::new(9216);[float[]]$expected=[float[]]::new(2304);[float[]]$actual=[float[]]::new(2304);[Buffer]::BlockCopy($expectedBytes,0,$expected,0,9216)
    $lines.Add('ArtifactsVerified=True');& $save
    $search=[IO.Path]::Combine($root,'qnn')+';/vendor/lib/rfsa/adsp;/vendor/dsp/cdsp;/dsp';foreach($name in 'ADSP_LIBRARY_PATH','DSP_LIBRARY_PATH'){[Environment]::SetEnvironmentVariable($name,$search);[Android.Systems.Os]::Setenv($name,$search,$true)}
    $native=[Runtime.InteropServices.NativeLibrary]::Load('libcdsprpc.so');$fn={param($Name,$ReturnType,$Parameters)$M::GetDelegateForFunctionPointer([Runtime.InteropServices.NativeLibrary]::GetExport($native,$Name),(& $abi.NewDelegateType ('AlbertAttention3_'+$Name) $ReturnType $Parameters))}
    $control=& $fn 'remote_session_control' ([int]) ([Type[]]@([uint32],[IntPtr],[uint32]));$open=& $fn 'remote_handle64_open' ([int]) ([Type[]]@([IntPtr],([uint64]).MakeByRefType()));$invoke=& $fn 'remote_handle64_invoke' ([int]) ([Type[]]@([uint64],[uint32],[IntPtr]));$close=& $fn 'remote_handle64_close' ([int]) ([Type[]]@([uint64]))
    $allocate={param([int]$Size)$ptr=$M::AllocHGlobal($Size);$allocations.Add(@($ptr,$Size));$M::Copy([byte[]]::new($Size),0,$ptr,$Size);$ptr};$pin={param([byte[]]$Bytes)$g=[Runtime.InteropServices.GCHandle]::Alloc($Bytes,[Runtime.InteropServices.GCHandleType]::Pinned);$pins.Add($g);$g.AddrOfPinnedObject()}
    $config=& $allocate 8;$M::WriteInt32($config,0,3);$M::WriteInt32($config,4,1);$rc=[int]$control.DynamicInvoke([object[]]@([uint32]2,$config,[uint32]8));if($rc-ne 0){throw 'Unsigned PD configuration failed'}
    $uri=[Text.Encoding]::UTF8.GetBytes('file:///libkokoro_albert_attention3_skel.so?kokoro_albert_attention3_skel_handle_invoke&_modver=1.0&_dom=cdsp'+[char]0);$uriPtr=& $pin $uri;$oa=[object[]]@($uriPtr,[uint64]0);$rc=[int]$open.DynamicInvoke($oa);if($rc-ne 0){throw 'Emitted attention library open failed'};$handle=[uint64]$oa[1];$opened=$true;$lines.Add('LibraryOpened=True');& $save
    $inputPtr=& $pin $inputBytes;$outputPtr=& $pin $output;$argsPtr=& $allocate 32;$M::WriteIntPtr($argsPtr,0,$inputPtr);$M::WriteInt64($argsPtr,8,27648);$M::WriteIntPtr($argsPtr,16,$outputPtr);$M::WriteInt64($argsPtr,24,9216);$call=[object[]]@($handle,[uint32]0x02010100,$argsPtr)
    $times=[double[]]::new(13);[double]$maxError=0;$maxIndex=-1
    for($iteration=0;$iteration-lt 13;$iteration++){$sw=[Diagnostics.Stopwatch]::StartNew();$rc=[int]$invoke.DynamicInvoke($call);$sw.Stop();if($rc-ne 0){throw "Attention invocation failed with rc=$rc"};$times[$iteration]=$sw.Elapsed.TotalMilliseconds;if($iteration-eq 0){[Buffer]::BlockCopy($output,0,$actual,0,9216);for($i=0;$i-lt 2304;$i++){if(-not[float]::IsFinite($actual[$i])){throw 'Non-finite DSP output'};$deltaError=[Math]::Abs([double]$actual[$i]-$expected[$i]);if($deltaError-gt$maxError){$maxError=$deltaError;$maxIndex=$i}};if($maxError-gt 0.00002){throw "DSP attention output exceeds tolerance: error=$maxError index=$maxIndex actual=$($actual[$maxIndex]) expected=$($expected[$maxIndex])"}}}
    [double[]]$warm=$times[1..12];[Array]::Sort($warm);$median=($warm[5]+$warm[6])/2;$lines.Add(('Values=2304 MaxError={0:R}'-f $maxError));$lines.Add(('WarmMedianMs={0:F3} WarmMinMs={1:F3} WarmMaxMs={2:F3}'-f $median,$warm[0],$warm[11]))
    $M::WriteInt64($argsPtr,8,27647);$rc=[int]$invoke.DynamicInvoke($call);$M::WriteInt64($argsPtr,8,27648);if($rc-ne 14){throw 'Length guard failed'}
    $saved=$M::ReadInt32($inputPtr);$M::WriteInt32($inputPtr,0,0x7f800000);$rc=[int]$invoke.DynamicInvoke($call);$M::WriteInt32($inputPtr,0,$saved);if($rc-ne 33){throw 'Input domain guard failed'}
    if((& $hash $inputBytes)-ne$fixture.GetProperty('Input').GetProperty('SHA256').GetString()){throw 'Input restoration failed'};$lines.Add('GuardsVerified=True');$passed=$true
}catch{$lines.Add('Error='+$_.Exception.Message);$lines.Add('At='+$_.InvocationInfo.ScriptLineNumber)}finally{if($opened){try{$rc=[int]$close.DynamicInvoke([object[]]@($handle));$lines.Add("CloseRc=$rc");if($rc-ne 0){$passed=$false}}catch{$passed=$false}};foreach($item in $allocations){$M::Copy([byte[]]::new([int]$item[1]),0,[IntPtr]$item[0],[int]$item[1]);$M::FreeHGlobal([IntPtr]$item[0])};foreach($pinHandle in $pins){if($pinHandle.IsAllocated){$pinHandle.Free()}};foreach($buffer in @($inputBytes,$expectedBytes,$output,$expected,$actual)){if($null-ne$buffer){[Array]::Clear($buffer,0,$buffer.Length)}};if($null-ne$document){$document.Dispose()};if($native-ne[IntPtr]::Zero){[Runtime.InteropServices.NativeLibrary]::Free($native)}}
$lines.Add("Passed=$passed");& $save;[void][Android.Util.Log]::Info('KokoroAlbertAttention3',($lines-join ' | '))
